# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9ed53e2326b5ed783355f3592dce2fc899235b61f0bc6f49810fe00de9379b28ec8e3ddd5f6f260d0ae062f37c8383f4daac33feb3ee38fef0ad4ee78b1842b1

test:
  secret_key_base: e501a5894781a309bfcc2ce51eccc0eebd721c2a5b2b44e7f80a308ebd896f32108218233267d2a9c39adb124845c8a0572d355fc3d09f6a2747717f1bbaed0b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
